services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    command: ["postgres", "-p", "5005"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: GPS
    ports:
      - '5005:5005'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5005
      DB_USERNAME: postgres
      DB_PASSWORD: 123123
      DB_NAME: GPS
    ports:
      - '3000:3000'
    volumes:
      - ./backend/uploads:/app/uploads

volumes:
  pgdata:
